/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prop.testing.ex1;

public class App {

    public static void main(String[] args) {
        System.out.println("Main called. This application does not do anything at runtime. Purely to showcase Property based testing");
    }
}
